
INSERT INTO DEPARTMENT
VALUES(4,'HR',65,'TVM');

INSERT INTO DEPARTMENT
VALUES(5,'HR',68,'KOCHI');
DESC DEPARTMENT;
SELECT*FROM DEPARTMENT;


SELECT upper(FIRST_NAME) FROM EMPLOYEE;
SELECT count(*)FROM DEPARTMENT WHERE DEPARTMENT_NAME='HR' ;
SELECT current_date();
SELECT SUBSTRING(first_name,1,4) FROM employee;
 SELECT MID(Address, 0, LOCATE('(',Address)) FROM DEPARTMENT;
 SELECT * FROM Employee WHERE Salary BETWEEN '5000' AND '100000';
 SELECT * FROM Employee WHERE FIRST_NAME LIKE 'S%';
 
 CREATE TABLE NEWONE LIKE DEPARTMENT;
 INSERT INTO NEWONE SELECT* FROM DEPARTMENT;
 SELECT* FROM NEWONE;
 SELECT concat(FIRST_NAME ,' ',LAST_NAME) As 'FullName' FROM EMPLOYEE;






